# -*- coding: utf-8 -*-
"""
Created on Tue0ct 26 12:39:43 2021

@author: wricw
"""
import csv
import os.path
from datetime import date


def savecsv(file, fldnames, content, datestamp: bool):
    if not os.path.isfile('data/' + file +'.cvs'):
        with open('data/' + file + '.cvs', 'w') as csv_file:
           writer = csv.DictWriter(csv_file, fieldnames=fldnames)
           writer.writeheader()
    with open('data/' + file + '.cvs', 'a+') as csv_file:
        if datestamp:
            if content['createdate'] == '':
                content['createdate'] = date.today()
            content['updatedate'] = date.today()
            writer = csv.DictWriter(csv_file, fieldnames=fldnames)
            writer.writerow(content)    


system = {'Charge' : ('Housing Charge','Rent'),
         'version': '0.0.0',
         'versionarea' : "Ontario Version",
          'baseelements': ['system', 'codes', 'members', 'units', 'connect'],
          'updatedate': '',
          'createdate': ''}
systemfn = ['Charge', 'version','versionarea','baseelements', 'updatedate', 'createdate']
savecsv('system', systemfn, system, True)

codes = {'incomesource':
         ('Earned', 'Single without Beneficiaries', 'Couples with/without Beneficiaries',
          'Single with Beneficiaries', 'ODSP'),
         'empexpt': 100,
         'percentofincomelabel': '30%',
         'percentofincomeamt': 0.30,
         'percentoh1stlabel': '15%',
         'percentoh1stamt': 0.15,
         'amt1st': 1000.00,
         'utilities': 1,
         'addionalchgs' : ('Sector Fee' , '5.00'),
         'treasurer': 'name',
         'updatedate': '',
         'createdate': ''
         }
codesfn = [ 'incomesource','empexpt','percentofincomelabel','percentofincomeamt','percentoh1stlabel', 'percentoh1stamt','amt1st' , 'utilities', 'AddchgsSector Fee', 'percentoh1stlabel''incomesource', 'empexpt', 'percentofincome', 'percentoh1st', 'amt1st',
           'utilities','utilitiesadd', 'percentoh1stlabel', 'addionalchgs', 'treasurer', 'updatedate', 'createdate']
savecsv('codes', codesfn, codes, True)
rawdata = {
    '1 - 1': {'NO.': '1', 'UNIT': '  1', 'FIRST NAME': '', 'LAST NAME': 'Gentles', 'FULL NAME': ' Gentles', 'ADDRESS': '1 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 1, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '2 - 1': {'NO.': '1', 'UNIT': '  2', 'FIRST NAME': '', 'LAST NAME': 'Romeo', 'FULL NAME': ' Romeo', 'ADDRESS': '2 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '3 - 1': {'NO.': '1', 'UNIT': '  3', 'FIRST NAME': '', 'LAST NAME': 'Poirier', 'FULL NAME': ' Poirier', 'ADDRESS': '3 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '4 - 1': {'NO.': '1', 'UNIT': '  4', 'FIRST NAME': '', 'LAST NAME': 'Johnson', 'FULL NAME': ' Johnson', 'ADDRESS': '4 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '5 - 1': {'NO.': '1', 'UNIT': '  5', 'FIRST NAME': 'Crystal', 'LAST NAME': 'Frey', 'FULL NAME': 'Crystal Frey', 'ADDRESS': '5- 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '6 - 1': {'NO.': '1', 'UNIT': '  6', 'FIRST NAME': '', 'LAST NAME': 'McNaul', 'FULL NAME': ' McNaul', 'ADDRESS': '6 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '7 - 1': {'NO.': '1', 'UNIT': '  7', 'FIRST NAME': '', 'LAST NAME': 'Benoit', 'FULL NAME': ' Benoit', 'ADDRESS': '7 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '8 - 1': {'NO.': '1', 'UNIT': '  8', 'FIRST NAME': '', 'LAST NAME': 'Mahamed', 'FULL NAME': ' Mahamed', 'ADDRESS': '8- 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '9 - 1': {'NO.': '1', 'UNIT': '  9', 'FIRST NAME': '', 'LAST NAME': 'Kocher', 'FULL NAME': ' Kocher', 'ADDRESS': '9 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 1, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '10 - 1': {'NO.': '1', 'UNIT': ' 10', 'FIRST NAME': '', 'LAST NAME': 'Griffith', 'FULL NAME': ' Griffith', 'ADDRESS': '10 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'updatedate': '', 'createdate':  ''},
    '11 - 1': {'NO.': '1', 'UNIT': ' 11', 'FIRST NAME': '', 'LAST NAME': 'Jozwiak', 'FULL NAME': ' Jozwiak', 'ADDRESS': '11 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 11'},
    '12 - 1': {'NO.': '1', 'UNIT': ' 12', 'FIRST NAME': '', 'LAST NAME': 'Swartz', 'FULL NAME': ' Swartz', 'ADDRESS': '12 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 12'},
    '13 - 1': {'NO.': '1', 'UNIT': ' 13', 'FIRST NAME': '', 'LAST NAME': 'Gebrehiwet', 'FULL NAME': ' Gebrehiwet', 'ADDRESS': '13 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 1, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 13'},
    '14 - 1': {'NO.': '1', 'UNIT': ' 14', 'FIRST NAME': '', 'LAST NAME': 'Elzein', 'FULL NAME': ' Elzein', 'ADDRESS': '14 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 14'},
    '14 - 2': {'NO.': '2', 'UNIT': ' 14', 'FIRST NAME': '', 'LAST NAME': 'Hussein', 'FULL NAME': ' Hussein', 'ADDRESS': '14 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 14'},
    '14 - 3': {'NO.': '3', 'UNIT': ' 14', 'FIRST NAME': '', 'LAST NAME': 'Ahmed', 'FULL NAME': ' Ahmed', 'ADDRESS': '14 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 14'},
    '15 - 1': {'NO.': '1', 'UNIT': ' 15', 'FIRST NAME': '', 'LAST NAME': 'Turcotte', 'FULL NAME': ' Turcotte', 'ADDRESS': '15 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 15'},
    '16 - 1': {'NO.': '1', 'UNIT': ' 16', 'FIRST NAME': '', 'LAST NAME': 'Najar', 'FULL NAME': ' Najar', 'ADDRESS': '13 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 16'},
    '16 - 2': {'NO.': '2', 'UNIT': ' 16', 'FIRST NAME': '', 'LAST NAME': 'Aboukakr', 'FULL NAME': ' Aboukakr', 'ADDRESS': '16 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 16'},
    '17 - 1': {'NO.': '1', 'UNIT': ' 17', 'FIRST NAME': '', 'LAST NAME': 'Nieuwesteeg', 'FULL NAME': ' Nieuwesteeg', 'ADDRESS': '14 - 436 Kingscourt Dr.', 'MARKET RENT': '$810.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Townhouse', 'Utilities benefit': ' $77.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 17'},
    '18 - 1': {'NO.': '1', 'UNIT': ' 18', 'FIRST NAME': '', 'LAST NAME': 'Griffith', 'FULL NAME': ' Griffith', 'ADDRESS': '15 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 1, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 18'},
    '19 - 1': {'NO.': '1', 'UNIT': ' 19', 'FIRST NAME': '', 'LAST NAME': 'March', 'FULL NAME': ' March', 'ADDRESS': '16 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 19'},
    '20 - 1': {'NO.': '1', 'UNIT': ' 20', 'FIRST NAME': '', 'LAST NAME': 'Hawco', 'FULL NAME': ' Hawco', 'ADDRESS': '17 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 20'},
    '21 - 1': {'NO.': '1', 'UNIT': ' 21', 'FIRST NAME': '', 'LAST NAME': '', 'FULL NAME': ' ', 'ADDRESS': '18 - 436 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 21'},
    '22 - 1': {'NO.': '1', 'UNIT': ' 22', 'FIRST NAME': 'Ric', 'LAST NAME': 'Woods', 'FULL NAME': 'Ric Woods', 'ADDRESS': '19 - 436 Kingscourt Dr.', 'MARKET RENT': '$810.00', 'MEMBER CLASS': 'PRIMARY', 'FAMILY SIZE': '4', 'INCOME SOURCE': 'Couples with/without beneficiaries', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Townhouse', 'Utilities benefit': ' $77.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 22'},
    '22 - 2': {'NO.': '2', 'UNIT': ' 22', 'FIRST NAME': 'john', 'LAST NAME': 'Woods', 'FULL NAME': 'john Woods', 'ADDRESS': '19 - 436 Kingscourt Dr.', 'MARKET RENT': '$810.00', 'MEMBER CLASS': 'PRIMARY', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Townhouse', 'Utilities benefit': ' $77.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 22'},
    '23 - 1': {'NO.': '1', 'UNIT': ' 23', 'FIRST NAME': '', 'LAST NAME': 'Lasko', 'FULL NAME': ' Lasko', 'ADDRESS': '20 - 436 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 23'},
    '24 - 1': {'NO.': '1', 'UNIT': ' 24', 'FIRST NAME': '', 'LAST NAME': 'Brito', 'FULL NAME': ' Brito', 'ADDRESS': '21 - 436 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 24'},
    '25 - 1': {'NO.': '1', 'UNIT': ' 25', 'FIRST NAME': '', 'LAST NAME': 'Akhtar', 'FULL NAME': ' Akhtar', 'ADDRESS': '22 - 456 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 25'},
    '26 - 1': {'NO.': '1', 'UNIT': ' 26', 'FIRST NAME': '', 'LAST NAME': 'Buelvas', 'FULL NAME': ' Buelvas', 'ADDRESS': '23 - 456 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 26'},
    '26 - 2': {'NO.': '2', 'UNIT': ' 26', 'FIRST NAME': '', 'LAST NAME': 'Barrios', 'FULL NAME': ' Barrios', 'ADDRESS': '26 - 456 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 26'},
    '27 - 1': {'NO.': '1', 'UNIT': ' 27', 'FIRST NAME': '', 'LAST NAME': 'Kortleve', 'FULL NAME': ' Kortleve', 'ADDRESS': '24 - 456 Kingscourt Dr.', 'MARKET RENT': '$810.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Townhouse', 'Utilities benefit': ' $77.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 27'},
    '28 - 1': {'NO.': '1', 'UNIT': ' 28', 'FIRST NAME': '', 'LAST NAME': '', 'FULL NAME': ' ', 'ADDRESS': '25 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 28'},
    '29 - 1': {'NO.': '1', 'UNIT': ' 29', 'FIRST NAME': '', 'LAST NAME': 'Arslan', 'FULL NAME': ' Arslan', 'ADDRESS': '26 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 29'},
    '30 - 1': {'NO.': '1', 'UNIT': ' 30', 'FIRST NAME': '', 'LAST NAME': 'Hazara', 'FULL NAME': ' Hazara', 'ADDRESS': '27 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 30'},
    '30 - 2': {'NO.': '2', 'UNIT': ' 30', 'FIRST NAME': '', 'LAST NAME': 'Saeed', 'FULL NAME': ' Saeed', 'ADDRESS': '30 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 30'},
    '31 - 1': {'NO.': '1', 'UNIT': ' 31', 'FIRST NAME': '', 'LAST NAME': 'Heer', 'FULL NAME': ' Heer', 'ADDRESS': '28 - 456 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 31'},
    '32 - 1': {'NO.': '1', 'UNIT': ' 32', 'FIRST NAME': '', 'LAST NAME': 'Edwards', 'FULL NAME': ' Edwards', 'ADDRESS': '29 - 456 Kingscourt Dr.', 'MARKET RENT': '$940.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '4 Bed Townhouse', 'Utilities benefit': ' $91.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 32'},
    '33 - 1': {'NO.': '1', 'UNIT': ' 33', 'FIRST NAME': '', 'LAST NAME': 'Koch', 'FULL NAME': ' Koch', 'ADDRESS': '30 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 33'},
    '34 - 1': {'NO.': '1', 'UNIT': ' 34', 'FIRST NAME': '', 'LAST NAME': 'Walsh', 'FULL NAME': ' Walsh', 'ADDRESS': '31 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 34'},
    '35 - 1': {'NO.': '1', 'UNIT': ' 35', 'FIRST NAME': '', 'LAST NAME': 'Peacock', 'FULL NAME': ' Peacock', 'ADDRESS': '32 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 35'},
    '36 - 1': {'NO.': '1', 'UNIT': ' 36', 'FIRST NAME': '', 'LAST NAME': 'Foote', 'FULL NAME': ' Foote', 'ADDRESS': '33 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 36'},
    '37 - 1': {'NO.': '1', 'UNIT': ' 37', 'FIRST NAME': '', 'LAST NAME': ' Lepetre', 'FULL NAME': '  Lepetre', 'ADDRESS': '34 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 37'},
    '38 - 1': {'NO.': '1', 'UNIT': ' 38', 'FIRST NAME': '', 'LAST NAME': 'Bowman', 'FULL NAME': ' Bowman', 'ADDRESS': '35 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 38'},
    '38 - 2': {'NO.': '2', 'UNIT': ' 38', 'FIRST NAME': '', 'LAST NAME': 'Langridge', 'FULL NAME': ' Langridge', 'ADDRESS': '37 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 38'},
    '39 - 1': {'NO.': '1', 'UNIT': ' 39', 'FIRST NAME': '', 'LAST NAME': 'Qamar', 'FULL NAME': ' Qamar', 'ADDRESS': '36 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 39'},
    '40 - 1': {'NO.': '1', 'UNIT': ' 40', 'FIRST NAME': '', 'LAST NAME': "O'Neil", 'FULL NAME': "0'Neil", 'ADDRESS': '37 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 40'},
    '40 - 2': {'NO.': '2', 'UNIT': ' 40', 'FIRST NAME': '', 'LAST NAME': 'Chapman', 'FULL NAME': ' Chapman', 'ADDRESS': '40 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 40'},
    '41 - 1': {'NO.': '1', 'UNIT': ' 41', 'FIRST NAME': '', 'LAST NAME': 'Daudlin', 'FULL NAME': ' Daudlin', 'ADDRESS': '38 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 41'},
    '42 - 1': {'NO.': '1', 'UNIT': ' 42', 'FIRST NAME': '', 'LAST NAME': 'Munene', 'FULL NAME': ' Munene', 'ADDRESS': '39 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 42'},
    '43 - 1': {'NO.': '1', 'UNIT': ' 43', 'FIRST NAME': '', 'LAST NAME': 'Boumar', 'FULL NAME': ' Boumar', 'ADDRESS': '40 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 43'},
    '43 - 2': {'NO.': '2', 'UNIT': ' 43', 'FIRST NAME': '', 'LAST NAME': 'Al-Timanl', 'FULL NAME': ' Al-Timanl', 'ADDRESS': '43 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 43'},
    '44 - 1': {'NO.': '1', 'UNIT': ' 44', 'FIRST NAME': '', 'LAST NAME': 'Asif', 'FULL NAME': ' Asif', 'ADDRESS': '41 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 44'},
    '45 - 1': {'NO.': '1', 'UNIT': ' 45', 'FIRST NAME': '', 'LAST NAME': 'Wheeler', 'FULL NAME': ' Wheeler', 'ADDRESS': '42 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 45'},
    '46 - 1': {'NO.': '1', 'UNIT': ' 46', 'FIRST NAME': '', 'LAST NAME': 'England', 'FULL NAME': ' England', 'ADDRESS': '43 - 456 Kingscourt Dr.', 'MARKET RENT': '$885.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '3 Bed Townhouse', 'Utilities benefit': ' $84.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'UNIT': ' 46'},
    '101 - 1': {'NO.': '1', 'UNIT': '101', 'FIRST NAME': '', 'LAST NAME': 'Mekuria', 'FULL NAME': ' Mekuria', 'ADDRESS': '44 - 456 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '101'},
    '102 - 1': {'NO.': '1', 'UNIT': '102', 'FIRST NAME': '', 'LAST NAME': 'ILC', 'FULL NAME': ' ILC', 'ADDRESS': '45 - 456 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '102'},
    '103 - 1': {'NO.': '1', 'UNIT': '103', 'FIRST NAME': '', 'LAST NAME': 'Unsworth', 'FULL NAME': ' Unsworth', 'ADDRESS': '46 - 456 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '103'},
    '104 - 1': {'NO.': '1', 'UNIT': '104', 'FIRST NAME': '', 'LAST NAME': 'McClellan', 'FULL NAME': ' McClellan', 'ADDRESS': '101 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '104'},
    '105 - 1': {'NO.': '1', 'UNIT': '105', 'FIRST NAME': '', 'LAST NAME': 'Sampson', 'FULL NAME': ' Sampson', 'ADDRESS': '102 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '105'},
    '106 - 1': {'NO.': '1', 'UNIT': '106', 'FIRST NAME': '', 'LAST NAME': 'Kellum', 'FULL NAME': ' Kellum', 'ADDRESS': '103 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '106'},
    '107 - 1': {'NO.': '1', 'UNIT': '107', 'FIRST NAME': '', 'LAST NAME': 'Boshart', 'FULL NAME': ' Boshart', 'ADDRESS': '104 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '107'},
    '108 - 1': {'NO.': '1', 'UNIT': '108', 'FIRST NAME': '', 'LAST NAME': 'Craigie', 'FULL NAME': ' Craigie', 'ADDRESS': '105 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '108'},
    '109 - 1': {'NO.': '1', 'UNIT': '109', 'FIRST NAME': '', 'LAST NAME': '', 'FULL NAME': ' ', 'ADDRESS': '106 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '109'},
    '110 - 1': {'NO.': '1', 'UNIT': '110', 'FIRST NAME': '', 'LAST NAME': 'Larsen', 'FULL NAME': ' Larsen', 'ADDRESS': '107 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '110'},
    '111 - 1': {'NO.': '1', 'UNIT': '111', 'FIRST NAME': '', 'LAST NAME': 'Stone', 'FULL NAME': ' Stone', 'ADDRESS': '108 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '111'},
    '112 - 1': {'NO.': '1', 'UNIT': '112', 'FIRST NAME': '', 'LAST NAME': 'Stone', 'FULL NAME': ' Stone', 'ADDRESS': '109 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '112'},
    '201 - 1': {'NO.': '1', 'UNIT': '201', 'FIRST NAME': '', 'LAST NAME': 'Wales', 'FULL NAME': ' Wales', 'ADDRESS': '110 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '201'},
    '202 - 1': {'NO.': '1', 'UNIT': '202', 'FIRST NAME': '', 'LAST NAME': 'Frank', 'FULL NAME': ' Frank', 'ADDRESS': '111 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '202'},
    '203 - 1': {'NO.': '1', 'UNIT': '203', 'FIRST NAME': '', 'LAST NAME': 'Deen', 'FULL NAME': ' Deen', 'ADDRESS': '112 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '203'},
    '204 - 1': {'NO.': '1', 'UNIT': '204', 'FIRST NAME': '', 'LAST NAME': 'Clayton', 'FULL NAME': ' Clayton', 'ADDRESS': '201 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '204'},
    '205 - 1': {'NO.': '1', 'UNIT': '205', 'FIRST NAME': '', 'LAST NAME': 'Mikel', 'FULL NAME': ' Mikel', 'ADDRESS': '202 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '205'},
    '206 - 1': {'NO.': '1', 'UNIT': '206', 'FIRST NAME': '', 'LAST NAME': 'Doerr', 'FULL NAME': ' Doerr', 'ADDRESS': '203 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '206'},
    '207 - 1': {'NO.': '1', 'UNIT': '207', 'FIRST NAME': '', 'LAST NAME': 'MacDonald', 'FULL NAME': ' MacDonald', 'ADDRESS': '204 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '207'},
    '208 - 1': {'NO.': '1', 'UNIT': '208', 'FIRST NAME': '', 'LAST NAME': 'Ryan', 'FULL NAME': ' Ryan', 'ADDRESS': '205 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit':  '308'},
    '209 - 1': {'NO.': '1', 'UNIT': '209', 'FIRST NAME': '', 'LAST NAME': 'Gaebel', 'FULL NAME': ' Gaebel', 'ADDRESS': '206 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '209'},
    '210 - 1': {'NO.': '1', 'UNIT': '210', 'FIRST NAME': '', 'LAST NAME': 'Heise', 'FULL NAME': ' Heise', 'ADDRESS': '207 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '210'},
    '211 - 1': {'NO.': '1', 'UNIT': '211', 'FIRST NAME': '', 'LAST NAME': 'Pulley', 'FULL NAME': ' Pulley', 'ADDRESS': '208 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '211'},
    '212 - 1': {'NO.': '1', 'UNIT': '212', 'FIRST NAME': '', 'LAST NAME': 'Cox', 'FULL NAME': ' Cox', 'ADDRESS': '209 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '212'},
    '213 - 1': {'NO.': '1', 'UNIT': '213', 'FIRST NAME': '', 'LAST NAME': 'Griffith', 'FULL NAME': ' Griffith', 'ADDRESS': '210 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '213'},
    '214 - 1': {'NO.': '1', 'UNIT': '214', 'FIRST NAME': '', 'LAST NAME': 'Meika', 'FULL NAME': ' Meika', 'ADDRESS': '211 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '214'},
    '215 - 1': {'NO.': '1', 'UNIT': '215', 'FIRST NAME': '', 'LAST NAME': 'Miller', 'FULL NAME': ' Miller', 'ADDRESS': '212 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '215'},
    '216 - 1': {'NO.': '1', 'UNIT': '216', 'FIRST NAME': '', 'LAST NAME': 'McDermott', 'FULL NAME': ' McDermott', 'ADDRESS': '213 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '216'},
    '301 - 1': {'NO.': '1', 'UNIT': '301', 'FIRST NAME': '', 'LAST NAME': '', 'FULL NAME': ' ', 'ADDRESS': '214 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '301'},
    '302 - 1': {'NO.': '1', 'UNIT': '302', 'FIRST NAME': '', 'LAST NAME': 'Riedl', 'FULL NAME': ' Riedl', 'ADDRESS': '215 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '302'},
    '303 - 1': {'NO.': '1', 'UNIT': '303', 'FIRST NAME': '', 'LAST NAME': 'Rhindress', 'FULL NAME': ' Rhindress', 'ADDRESS': '216 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '303'},
    '304 - 1': {'NO.': '1', 'UNIT': '304', 'FIRST NAME': 'Julie', 'LAST NAME': 'England', 'FULL NAME': 'Julie England', 'ADDRESS': '301 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': 'PRIMARY', 'FAMILY SIZE': '1', 'INCOME SOURCE': 'ODSP', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '304'},
    '305 - 1': {'NO.': '1', 'UNIT': '305', 'FIRST NAME': '', 'LAST NAME': 'Griffith', 'FULL NAME': ' Griffith', 'ADDRESS': '302 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '305'},
    '306 - 1': {'NO.': '1', 'UNIT': '306', 'FIRST NAME': '', 'LAST NAME': 'Perry', 'FULL NAME': ' Perry', 'ADDRESS': '303 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '306'},
    '307 - 1': {'NO.': '1', 'UNIT': '307', 'FIRST NAME': '', 'LAST NAME': 'Hanna', 'FULL NAME': ' Hanna', 'ADDRESS': '304 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '307'},
    '308 - 1': {'NO.': '1', 'UNIT': '308', 'FIRST NAME': '', 'LAST NAME': 'Wright', 'FULL NAME': ' Wright', 'ADDRESS': '305 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '308'},
    '309 - 1': {'NO.': '1', 'UNIT': '309', 'FIRST NAME': '', 'LAST NAME': 'Stone', 'FULL NAME': ' Stone', 'ADDRESS': '306 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '309'},
    '310 - 1': {'NO.': '1', 'UNIT': '310', 'FIRST NAME': '', 'LAST NAME': 'Garrah', 'FULL NAME': ' Garrah', 'ADDRESS': '307 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '310'},
    '311 - 1': {'NO.': '1', 'UNIT': '311', 'FIRST NAME': '', 'LAST NAME': 'Cantley', 'FULL NAME': ' Cantley', 'ADDRESS': '308 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '311'},
    '312 - 1': {'NO.': '1', 'UNIT': '312', 'FIRST NAME': '', 'LAST NAME': 'Duke', 'FULL NAME': ' Duke', 'ADDRESS': '309 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 1, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '312'},
    '313 - 1': {'NO.': '1', 'UNIT': '313', 'FIRST NAME': '', 'LAST NAME': 'Verlegh', 'FULL NAME': ' Verlegh', 'ADDRESS': '310 - 446 Kingscourt Dr.', 'MARKET RENT': '$630.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '1 Bed Apartment', 'Utilities benefit': ' $45.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '313'},
    '314 - 1': {'NO.': '1', 'UNIT': '314', 'FIRST NAME': '', 'LAST NAME': 'Griffin', 'FULL NAME': ' Griffin', 'ADDRESS': '311 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '314'},
    '315 - 1': {'NO.': '1', 'UNIT': '315', 'FIRST NAME': '', 'LAST NAME': 'Ronnenberg', 'FULL NAME': ' Ronnenberg', 'ADDRESS': '312 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '315'},
    '316 - 1': {'NO.': '1', 'UNIT': '316', 'FIRST NAME': '', 'LAST NAME': 'Ghafar', 'FULL NAME': ' Ghafar', 'ADDRESS': '313 - 446 Kingscourt Dr.', 'MARKET RENT': '$695.00', 'MEMBER CLASS': '', 'FAMILY SIZE': '', 'INCOME SOURCE': '', 'INCOME AMOUNT': '', 'EMP. EXEMPT': 0, 'UNIT TYPE': '2 Bed Apartment', 'Utilities benefit': ' $47.00 ', 'Apply': 1, 'updatedate': '', 'createdate':  '', 'Unit': '316'}
}
members = {}
memberlist = []
units = {}
unitlist = []
connect = {}
for item in rawdata:
    fullname = rawdata[item]['FIRST NAME'] + ' ' + rawdata[item]['LAST NAME']
    unit = int(rawdata[item]['UNIT'])
    stripunit = rawdata[item]['UNIT'].lstrip
    address = rawdata[item]['ADDRESS']
    address = address.split("- ", 4)
    streetno = address[1][:3]
    streetname = 'Kingscourt Dr.'
    city = 'Waterloo'
    prov = 'Ontario'
    pc = ' '
    if streetno == '436':
        pc = 'N3K 3R8'
    if streetno == '446':
        pc = 'N3K 3R9'
    if streetno == '466':
        pc = 'N3K 3S1'
    address = rawdata[item]['UNIT'] + ' - ' + streetno + ' ' + streetname
    fulladdress = rawdata[item]['UNIT'] + ' - ' + \
        streetno + ' ' + streetname + ' ' + city + ' ' + pc
    members = {'fullname': fullname,
               'memberclass' : rawdata[item]['MEMBER CLASS'],
               'familsize' : rawdata[item]['FAMILY SIZE'],
               'incomesource' : rawdata[item]['INCOME SOURCE'],
               'incomeamount' : rawdata[item]['INCOME AMOUNT'],
               'enpexempt' : rawdata[item]['EMP. EXEMPT'],
               'updatedate' : rawdata[item]['updatedate'],
               'createdate' : rawdata[item]['createdate']
              }
    memberlist.append(fullname)

    units  = {'unit' :unit,
       'address' : address,
       'fulladdress' : fulladdress,
       'marketrent' : rawdata[item]['MARKET RENT'],
       'unittype' : rawdata[item]['UNIT TYPE'],
       'Utilities benefit' : '',
       'Apply' : 1,
       'updatedate' : rawdata[item]['updatedate'],
       'createdate' : rawdata[item]['createdate']
                   } 
    unitlist.append(unit)

    connect  = {
                  'member' : rawdata[item]['FULL NAME'],
                  'unit' : rawdata[item]['UNIT'],
                  'updatedate' : rawdata[item]['updatedate'],
                  'createdate' : rawdata[item]['createdate']
                }
    membersfn = ['fullname','memberclass', 'familsize', 'incomesource',
             'incomeamount', 'enpexempt', 'updatedate', 'createdate']
    unitsfn = ['unit','address', 'fulladdress', 'marketrent', 'unittype',
           'Utilities benefit', 'Apply', 'updatedate', 'createdate']
    connectfn = ['member', 'unit', 'updatedate', 'createdate']
    savecsv('members', membersfn, members, True)
#   savecsv('members',memberlist,False)
    savecsv('units', unitsfn, units, True)
    savecsv('connect',connectfn, connect, True)
